<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<?php if($this->getBoletoUrl()): ?>
<br />
<a href="<?php echo $this->getBoletoUrl() ?>" target="_blank"><? echo $this->__('Click here to print your Boleto') ?></a>
<?php endif ?>

<?php echo $this->getChildHtml()?>