<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<?php if ($this->getInfo()):?>
<p><?php echo $this->__('Credit Card Type') ?>: <br /><?php echo $this->escapeHtml($this->getCcTypeName()) ?></p>
<p><?php echo $this->__('Name on the Card') ?>: <br /><?php echo $this->escapeHtml($this->getCcOwner()) ?></p>
<p><?php echo $this->__('Credit Card Number') ?>: <br /><?php echo $this->escapeHtml($this->getCcNumber()) ?></p>
<p><?php echo $this->__('Installments') ?>: <?php echo $this->escapeHtml($this->getInstallments()) ?>x</p>
<?php endif;?>

<?php echo $this->getChildHtml()?>