<!--<script type="text/javascript" src="https://pagar.me/assets/pagarme.js"></script> -->
<script type="text/javascript" src="<?php echo $this->getJsUrl('pagarme/prototype/validation.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pagarme/js/checkout.js') ?>"></script>
<!-- <script type="text/javascript">PagarMe.encryption_key = '<?php // echo $this->helper('pagarme')->getEncryptionKey() ?>';</script> -->
<script type="text/javascript">
var pagarme_encryption_key = "<?php echo $this->helper('pagarme')->getEncryptionKey() ?>";
</script>

