<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li style="display: none;"><input type="hidden" id="<?php echo $_code ?>_pagarme_card_hash" name="payment[pagarme_card_hash]" value="" /></li>
    <li>
        <label for="<?php echo $_code ?>_installments" class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_installments" name="payment[installments]" title="<?php echo $this->__('Installments') ?>" class="required-entry validate-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php $_installments = $this->getInfoData('installments') ?>
            <?php foreach ($this->getInstallmentsAvailables() as $_installmentValue => $_installmentLabel): ?>
                <option value="<?php echo $_installmentValue ?>"<?php if($_installmentValue==$_installments): ?> selected="selected"<?php endif ?>><?php echo $_installmentLabel ?></option>
            <?php endforeach ?>
            </select>
            <input type="hidden" id="<?php echo $_code ?>_installment_description" name="payment[installment_description]" value="<?php echo $this->escapeHtml($this->getInfoData('installment_description')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" class="month validate-cc-exp required-entry">
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
</ul>
<script type="text/javascript">
    payment.loadPagarmeCcData();
    $('pagarme_cc_installments').observe('change', function(){
        var index = this.selectedIndex;
        if (index > 0) {
            $('pagarme_cc_installment_description').value = this.options[index].text;
        } else {
            $('pagarme_cc_installment_description').value = '';
        }
    });
</script>
