<ul class="form-list" id="payment_form_pagarme_checkout" style="display:none;">
    <input type="hidden" value="" name="payment[pagarme_checkout_token]" id="pagarme_checkout_token" class="required_entry" />
    <input type="hidden" value="" name="payment[pagarme_checkout_payment_method]" id="pagarme_checkout_payment_method" />

    <div style="display:none;" id="advice-required-entry-pagarme-checkout-hash" class="validation-advice">
        <?php echo __("Please click the button below<br />and complete the information."); ?>
    </div>

    <button id="pagarme-checkout-fill-info-button" class="button" type="button">
        <span><span><?php echo __('Fill in the card data'); ?></span></span>
    </button>
</ul>

<script type="text/javascript" id="pagarme-checkout">
    $("pagarme-checkout-fill-info-button").observe("click", function (event){
        var checkoutPagarme = new PagarMeCheckout.Checkout({
            "encryption_key" : "<?= $this->getEncryptionKey() ?>",
            success: function (response) {
                $('pagarme_checkout_token').value = response['token'];
                $('pagarme_checkout_payment_method').value = response['payment_method'];
            }
        });

        checkoutPagarme.open(<?= $this->getCheckoutConfig() ?>);
    });
</script>
