<?php
    $transaction = \Mage::getModel('pagarme_core/service_order')
        ->getTransactionByOrderId($this->getOrder()->getId());

    $paymentMethodWasCreditCard = $this->getOrder()->getPayment()->getMethod() ===
        PagarMe_CreditCard_Model_Creditcard::PAGARME_CREDITCARD;
    $paymentHasInterest = $transaction->getRateAmount() > 0;
    $shouldShow = $paymentMethodWasCreditCard && $paymentHasInterest;
?>

<?php if ($shouldShow): ?>
    <tr id="pagarme_creditcard_order_info_rate_amount">
        <td class="label">
            <?=
                Mage::helper('pagarme_creditcard')
                    ->__('Installments related Interest')
            ?>
        </td>
        <td>
            <?=
                $this->displayPrices(
                    $transaction->getRateAmount(),
                    $transaction->getRateAmount()
                )
            ?>
        </td>
    </tr>
<?php endif; ?>
